apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromcode
  name: nginx-yaml
spec:
  containers:
    - image: nginx
      name: nginx-yaml
      volumeMounts:
        - mountPath: "/app/data"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: mealie-data
