apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: postgresql
type: Opaque
stringData:
  POSTGRES_USER: "shawn47"
  POSTGRES_PASSWORD: "Hi1/cosc"
  POSTGRES_DB: "postgresdb"
  REPLICATION_USER: "replicationuser"
  REPLICATION_PASSWORD: "replicationPassword"
